const PolicyEvents = Object.freeze({
  POLICY_EVALUATED: 'POLICY_EVALUATED',
  POLICY_SHADOW_EXECUTED: 'POLICY_SHADOW_EXECUTED',
  POLICY_EXPLANATION_RECORDED: 'POLICY_EXPLANATION_RECORDED',
  POLICY_OBSERVABILITY_SNAPSHOT: 'POLICY_OBSERVABILITY_SNAPSHOT'
});

export default PolicyEvents;
