const RiskEvents = Object.freeze({
  RISK_CLASSIFIED: 'RISK_CLASSIFIED',
  RISK_ESCALATION_RECOMMENDED: 'RISK_ESCALATION_RECOMMENDED',
  RISK_EXPLANATION_RECORDED: 'RISK_EXPLANATION_RECORDED',
  RISK_OBSERVABILITY_SNAPSHOT: 'RISK_OBSERVABILITY_SNAPSHOT'
});

export default RiskEvents;
