const IdentityEvents = Object.freeze({
  OPERATOR_CREATED: 'OPERATOR_CREATED',
  OPERATOR_UPDATED: 'OPERATOR_UPDATED',
  OPERATOR_DISABLED: 'OPERATOR_DISABLED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',
  IDENTITY_RESOLVED: 'IDENTITY_RESOLVED',
  IDENTITY_RESOLUTION_FAILED: 'IDENTITY_RESOLUTION_FAILED',
  IDENTITY_AUDIT_CREATED: 'IDENTITY_AUDIT_CREATED',
  IDENTITY_VALIDATION_STARTED: 'IDENTITY_VALIDATION_STARTED',
  IDENTITY_VALIDATION_COMPLETED: 'IDENTITY_VALIDATION_COMPLETED',
  IDENTITY_VALIDATION_FAILED: 'IDENTITY_VALIDATION_FAILED'
});

module.exports = IdentityEvents;
