const PermissionEvents = Object.freeze({
  PERMISSIONS_RESOLVED: 'PERMISSIONS_RESOLVED',
  PERMISSION_OBSERVED: 'PERMISSION_OBSERVED',
  ROLE_PERMISSION_OBSERVED: 'ROLE_PERMISSION_OBSERVED'
});

export default PermissionEvents;
